language: node_js
node_js:
    - node
script: npm run build
deploy:
    provider: firebase
    skip_cleanup: true
    token:
        secure: NEoOhi2CjrQv93/OEgDnweGptW8K2kAg4EKGb1NevAGt4CO7p7jhv7/AuJNPiEUZsfmEKBSdPebEeKpFSMAXNJ5OV0AP+JhUAc9AMwKWx8M078AgNtxJZHVoVdruW/07ExTzpxPxIBHOCybPDt1BO4TBU79tQzwTuRShZhSsevoaxa+BJXCH61SxEbOpKYM742lr25ulmu9kopVZuI6Ud3RWubHGmDuJu5lPz5aldMIKs3muWGDTQwEgjF+3b5ZYkXopsuM0OiDZtdaVzWEVfl+nuzXyJJEoEmV/1vk6InqhPIg5zAjJPSrwl45QJ1/h5v7Htq6e+1bKGffjKwEwUjzaPgzLz3BIzWpamzMtSjJegCLXiKR3NbeR580G8prAWuGMrth0qmgqyhpycXjwFH3JqP40kM3sLkEw9yGwS6zcNDegV0sjkqIZNjDEUu05ZG1gkKVh1NZeA0Q7HTCGjoCFEwqkCn1ZXuCobDvfpcypsRA1ZuWNnc8ZtAzX9CCh5VOD2+J+DbdAUnBTBl09e1sbBREOd6+dvWFQlL0bQSXmYWw03LV+dYuuAq8waRfzUtkeEehNIt0ZYKxjmnABMTm29Ylm+/oJ2rftPhzlQMGzWZpYhBQnHkwQPWsW+LEGCK7Im1je0DbCEV5zKuU9U7peKXwAyduycaDUw7HjFcM=
    on:
        branch: master
